// Auto-generated by @gulibs/vite-plugin-i18n - Do not edit manually!
// Generated at: 2025-06-14T20:38:43.937Z

/**
 * 所有可用的翻译键
 */
export const i18nKeys = [
  "common.app.description",
  "common.app.title",
  "common.common.language",
  "common.common.loading",
  "common.common.welcome"
] as const;

/**
 * 翻译键的联合类型
 */
export type I18nKeys = 'common.app.description' | 'common.app.title' | 'common.common.language' | 'common.common.loading' | 'common.common.welcome';

export default i18nKeys;
